name: Test Concurrency
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
concurrency:
  group: ci-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github event name: ${{ github.event_name }}"
      - if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "=pr github event name: ${{ github.event_name }}"
      - if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "!= pr github event name: ${{ github.event_name }}"
      - if: ${{ !github.event_name == 'pull_request' }}
        run: |
          echo "!pr= github event name: ${{ github.event_name }}"

  # Note: This job name MUST NOT CHANGE without also updating RAPID
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Print concurrency
        run: |
          echo "Concurrency group: ci-${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
      - name: Wait a bit
        run: |
          sleep 300
